### ISSUE TITLE
The menu item 'Acknowledgements' needs to change

### ISSUE THREAD

**Issue by jduteau** [HL7/vulcan-rwd#1]
The page for Acknowledgements has more than acknowledgements so the name should change or the content should be split out.

**Comment by mike-hamidi** [comment]
Agreed. It should be split into "Related References" and "Acknowledgements" - or the like.

**Comment by jduteau** [comment]
https://github.com/HL7/vulcan-rwd/commit/0324544c9febb8bd6365ed42bbddcab62751976c fixes this
