### ISSUE TITLE
FHIR-to-CDISC Link

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/vulcan-rwd#4]
**URL**: http://build.fhir.org/ig/HL7/vulcan-rwd/index.html#current-scope
**Comment**: Can we have a direct link to http://hl7.org/fhir/uv/cdisc-mapping/STU1/ for the 1st paragraph (last sentence) stating "FHIR to CDISC Joint Mapping Implementation Guide"

Note: If these references exist under Appendices, then linking to this page (see separate issue) may be helpful. For instance, I also see the reference to IPS in this section.

**Comment by jduteau** [comment]
https://github.com/HL7/vulcan-rwd/commit/ed9899c71b55c97d7a3be74d851d53370d57b6e8 adds the direct link.
