### ISSUE TITLE
Technical Considerations

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/vulcan-rwd#8]
**URL**: http://build.fhir.org/ig/HL7/vulcan-rwd/technical.html#representing-absent-and-not-known-data
**Comment**: 
Is the intent for Section 5.1 to describe that although the RWD IG may not use the IPS in totality, those expectations from an operational perspective should be acknowledged? For example, RWD does not use "Allergies and Intolerances" but IPS [AllergyIntolerance.code] (https://hl7.org/fhir/uv/ips/StructureDefinition-AllergyIntolerance-uv-ips-definitions.html#AllergyIntolerance.code) is required to be present in a conforming FHIR server.

**Comment by jduteau** [comment]
The intent is to say, in accordance with the IPS guide, that sections that are required to be present need to indicate, when there is no data, whether there is no data because there is known to be no X for the patient or not.
